export const openCopy = {
  heading: "正在打开 AstroBox 客户端",
  prompt: "如果您的浏览器弹出询问提示框，请点按打开",
  autoOpenFailed: "您的浏览器没有自动打开吗？",
  retry: "重试",
  openWeb: "用网页版打开",
  notInstalled: "还没有安装 AstroBox 吗？",
  goDownload: "前往下载页",
  qrCaption: "扫描二维码\n打开 AstroBox 手机端",
  debugTitle: "调试信息",
  enabled: "已启用调试模式，当前不会自动跳转。",
  debugUserAgent: "用户代理",
  debugEnvironment: "当前环境",
  debugStrategy: "打开策略",
  debugFinalLink: "最终链接",
  debugSchemeLink: "协议链接",
  debugServerLink: "本地服务链接",
  debugAutoRedirect: "自动跳转",
  retryWithScheme: "使用协议链接打开",
  retryWithServer: "使用本地服务打开",
  mobile: "移动端",
  desktop: "桌面端",
  scheme: "直接使用协议链接",
  server: "优先使用本地服务链接",
  schemeWithFallback: "先使用协议链接，随后回退到本地服务链接",
  enabledValue: "已关闭",
  disabledValue: "已开启",
};
